name: ccc

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: cinnaahml
          password: 96962ed6-97e5-4f65-b30d-538e1f343439
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: cinnaahml/flask-demo:latest
